instill-ai/api-gateway

config/settings-env/endpoints.json

Because
- `model-backend` has a readiness status pre-conditioning on Temporal `add-search-attributes`
This commit
- add the readiness check endpoint

chore(model): add readiness endpoint

---

config/settings-env/endpoints.json

Because
- some generative models have huge file size, then take a long time to upload the model into the model-backend
This commit
- increase time of creating and inferencing model endpoint in the model-backend

chore: increase timeout for creating and infer model endpoint

---

config/settings-env/endpoints.json

Because
- requests for pipeline trigger endpoints need longer time when dealing with diffusion models
This commit
- increase the pipeline trigger endpoint timeout

chore: increase timeout for trigger pipeline endpoint

---

config/settings-env/endpoints.json

Because
- we want to remove the concept of the model instance
This commit
- replace the model instance endpoints with corresponding model deploy/undeploy/trigger endpoints
fix INS-387

chore(model): remove model instance endpoints

---

config/settings-env/endpoints.json

Because
- support watch endpoints for resource state monitoring
This commit
- add watch endpoints for pipeline, connector and model backend

chore(pipeline, connector, model): add endpoints for /watch

---

config/settings-env/endpoints.json

Because
- the Temporal does not support search attributes
This commit
- remove list and cancel operation method in the model backend

chore(model): update model operation methods

---

config/settings-env/endpoints.json

Because
- we separated the sync/async endpoints for pipeline trigger, need to update this in gateway.
This commit
- add triggerSync and triggerAsync endpoints

chore(pipeline): add triggerSync and triggerAsync endpoints

---

config/settings-env/endpoints.json

Because
- update now sync endpoint's timeout
This commit
- update now sync endpoint's timeout

chore(connector): update sync endpoint timeout

---

config/templates/opencensus.tmpl

Because
- export metrics failed because of invalid metric name with "-"
This commit
- fix it and replace with underscore

chore(metrics): fix invalid metric naming prefix

---

config/settings-env/endpoints.json

Because
- we changed `WriteDestinationConnector` and `ReadSourceConnector` to `ExecuteDestinationConnector` and `ExecuteSourceConnector`
This commit
- update connector endpoints

chore(connector): update connector endpoints

---

config/settings-env/endpoints.json

Because
- the original source-connectors/destination-connectors endpoints are basically the same. And since we will have more types of connector in the future. Adding more endpoints is not a good choices.
This commit
- unify connectors endpoints

chore(connector): unify connectors endpoints

---

config/settings-env/endpoints.json

Because
- we added a new filter param for connectors and connector-definitions endpoints
This commit
- propagate the `filter`

chore(connector): add input_query_strings `filter` for connectors and connector-definitions

---

Dockerfile

Because
- the image build is broken
This commit
- fix the wrong `WORKDIR`

ci: fix Dockerfile

---

config/vdp/settings-env/endpoints.json

Because
- we want to simplify the `triggerSync` endpoint to `trigger`
- add a get result endpoint for `triggerAsync`
This commit
- rename `triggerSync` to `trigger`
- add GET `operation` endpoint

chore(vdp): update trigger and operation endpoints

---

config/base/settings-env/endpoints.json

Because
- support connector dashboard
- support time window aggregation for dashboard chart render
This commit
- add chart and connector metric endpoints

chore(vdp): add connector and metric endpoints

---

config/base/settings-env/endpoints.json

Because
- add missing query string for listing charts
This commit
- add missing query string for listing charts

chore(metric): add missing query string for listing charts

---

config/vdp/settings-env/endpoints.json

Because
- we need a new endpoint for operator-definitions
This commit
- add operator-definitions endpoint

chore(vdp): add operator-definitions endpoint

---

config/vdp/settings-env/endpoints.json

Because
- In order to prevent confusion, we are going to rename connector to connector-resource.
This commit
- rename connector to connector-resource

chore(vdp): rename connector to connector-resource

---

config/vdp/settings-env/endpoints.json

Because
- We would like to make the resources be public or shared to other users. The current structure can not support it since the api endpoint was designed for the users' own resources.
This commit
- refactor endpoints to support namespace

chore(vdp): add namespace in endpoints

---

config/model/settings-env/endpoints.json

Because
- We would like to make the model resources be public or shared to other
users. The current structure can not support it since the api endpoint
was designed for the users' own resources.
This commit
- refactor model endpoints to support namespace

chore(model): adopt namespace in endpoints

---

config/model/settings-env/endpoints.json
config/vdp/settings-env/endpoints.json

Because
- The lookup endpoints use `uuid` for query, we don't need namespace for it.
This commit
- remove namespace from lookup endpoints

chore(vdp): remove namespace from lookup endpoints

---

config/model/settings-env/endpoints.json
config/vdp/settings-env/endpoints.json

Because
- we added a `show_deleted` query param for the list operations in backend
This commit
- propagate `show_deleted` query param
- expose pipeline validation endpoint

chore(vdp): propagate `show_deleted` query param

---

config/share/settings-env/input_headers.json

Because
- we have a header `instill-return-traces`
This commit
- propagate `instill-return-traces` header into backend

chore(base,vdp,model): propagate `instill-return-traces` header into backend

---

config/share/templates/cors.tmpl

Because
- the CORS setting is not working for header `Instill-Return-Traces`
This commit
- add `Instill-Return-Traces` and `Access-Control-Allow-Headers` into CORS allow headers

chore(base): add `Instill-Return-Traces` to allow_headers in CORS setting

---

Dockerfile

Because
- we should cross-compile the `jwx` tool
This commit
- fix api gateway `jwx` tool failed in arm64

fix(auth): fix api gateway `jwx` tool failed in arm64

---

config/share/settings-env/input_headers.json
config/share/templates/cors.tmpl

Because
- we need `Instill-Code` header as additional authorization code
This commit
- add `Instill-Code` header

chore(base): add `Instill-Code` header

---

config/share/settings-env/input_headers.json
config/share/templates/cors.tmpl

Because
- the original header `Instill-Code` doesn't have a clear meaning
This commit
- rename header `Instill-Code` to `Instill-Share-Code`

chore(base): rename header `Instill-Code` to `Instill-Share-Code`

---

.github/CONTRIBUTING.md
Dockerfile
config/base/settings-env/endpoints.json

Because
- the path of `setDefault` is wrong
This commit
- fix pipeline release `setDefault` endpoint
- fix go build params for plugin

fix(base): fix pipeline release `setDefault` endpoint

---

multi_auth_plugin/go.mod
multi_auth_plugin/server/main.go

Because
- we don't need to re-order HTTP trailer in multi-auth plugin, it will be handled by grpc-proxy plugin 
- there are memory-leak risks when creating http client for every request
This commit
- fix `writeStatusUnauthorized` func
- update multi-auth plugin package name
- re-use http client

chore(plugin): optimize multi-auth plugin

---

config/settings-env/endpoints.json

Because
- delete model takes longer for `ray` model
This commit
- prolong timeout for deleteusermodel

chore(model): prolong timeout for deleteusermodel

---

config/settings-env/endpoints.json

Because
- we need an API to determine the availability of a namespace id and its type
This commit
- remove ExistUsername API  and add new CheckNamespace API

refactor(core): retire ExistUsername API and add CheckNamespace API

---

config/settings-env/endpoints.json
multi_auth_plugin/go.mod
multi_auth_plugin/go.sum
multi_auth_plugin/server/main.go

Because
- We need to allow some endpoints reachable without login, we decided to generate a random uuid for identifying the visitor. We'll also use this visitor id for rate-limit purpose in the future
This commit
- inject visitor id for public endpoints
- fix connector endpoint bug

feat(plugin): inject visitor id for public endpoints

---

Dockerfile

Because
- The go plugin can't work due to the golang version mismatch. Our plugin need to use `go:1.21`, but the Krakend image is built from `go:1.20`
This commit
- build Krakend from source to fix golang vesion mismatch

fix(dockerfile): build Krakend from source to fix golang vesion mismatch

---

Dockerfile

Because
- avoid having root as owner with service folder
This commit
- use `nobody:nogroup` as default user

chore(dockerfile): update default user

---

Dockerfile

Because
- the CI-built images has cross-compiling issues
This commit
- fix cross compiling issues

fix(dockerfile): fix cross compiling issues

---

config/settings-env/endpoints.json

Because
- we have a new query param for GET /pipelines endpoint
This commit
- propagate `visibility` query param for GET /pipelines endpoint

feat(vdp): propagate `visibility` query param for GET /pipelines endpoint

---

grpc_proxy_plugin/pkg/client.go

Because
- The TCP connections didn't close in grpc-proxy, causing connection leak.
This commit
- Fix TCP connection leak

fix(plugin): fix TCP connection leak

---

.github/workflows/integration-test.yml

Because
- we retire `controller-vdp`
- `controller-model` does not have exposed endpoint to test
This commit
- remove `controller-vdp` and `controller-model` from test component list

ci(workflows): remove controller test

---

config/settings-env/endpoints.json

Because
- we have a `visibility` query param for list pipelines endpoints in pipeline-backend
This commit
- add `visibility` query param for list pipelines endpoints

feat(vdp): add visibility query param for list pipelines endpoints

---

config/settings-env/endpoints.json

Because
- We want to provide an API to let user clone the pipeline recipe.
This commit
- Add `CloneUserPipeline` and `CloneOrganizationPipeline` endpoints

feat(vdp): add `CloneUserPipeline` and `CloneOrganizationPipeline` endpoints

---

config/settings-env/endpoints.json

Because
- We want to provide an endpoint to let Console check the availability of pipeline or connector name.
This commit
- Add `CheckName` endpoint

feat(vdp): add `CheckName` endpoint

---

config/settings-env/endpoints.json

Because
- We need an endpoint for getting authenticated users' own data.
This commit
- Adds a new `GetAuthenticatedUser` endpoint for getting authenticated users' own data.

feat(mgmt): refactor API for `GET` and `PATCH` authenticated user

---

config/settings-env/endpoints.json

Because
- Website needs to access a paginated list of components
This commit
- Opens the endpoint introduced in https://github.com/instill-ai/protobufs/pull/274

feat(vdp): add component definition list endpoint

---

.github/workflows/integration-test.yml
config/base.json

Because
- load balancer provided by a cloud vendor supports only certain TLS versions
This commit
- add the `min_version` and `max_version` variables in the `tls` block

chore(config): add tls version

---

config/share/settings-env/input_headers.json

Because
- The Instill Model connector can't work properly in internal mode since the pods in different region clusters can't connect to each other, we decided to use external IP and bypass the user authorization.
This commit
- Fixes the multi-region connection problem by bypassing the user authorization header.

chore(core): forward authorization header

---

config/settings-env/endpoints.json

Because
- we are going to support asynchronous call for model trigger
This commit
- add model trigger async endpoints

feat(model): add model async trigger

---

plugins/registry/handler.go

Because
- `model-backend:latest` returns a `NotFound` when the model doesn't exist. API gateway was capturing `Unavailable`.
This commit
- Updates the error code
@heiruwu I don't know why when I was QAing this I was receiving an `Unavailable` code but having a look at the [source code](https://github.com/instill-ai/model-backend/blob/main/pkg/service/service.go#L344) a missing namespace should return `NotFound`, right? Or am I looking at the wrong method?

fix(registry): capture NotFound response in namespace check

---

config/settings-env/endpoints.json

Because
- Putting the avatar as base64 in the pipeline response is not a good choice. We should provide a link for the Console to fetch the avatar asynchronously.
This commit
- Adds endpoints for user and organization avatars.

feat(mgmt): add endpoints for user and organization avatars

---

config/settings-env/endpoints.json

Because
- We are going to provide a feature that allows users to store secrets under their own namespace or the organization namespaces, the pipeline recipe can reference these secrets.
This commit
- Exposes pipeline secrets endpoints.

feat(vdp): expose pipeline secrets endpoints

---

config/settings-env/endpoints.json

Because
- https://github.com/instill-ai/protobufs/pull/304 introduced the public credit endpoint for getting the remaining credit
This commit
- Add public endpoints (HTTP, gRPC) to `api-gateway`

feat(mgmt): add credit public endpoints

---

config/settings-env/endpoints.json

Because
- The Credit API should only be exposed on the Cloud services. Since Credit is used to execute connectors with the Instill secrets, CE users won't be able to use credit.
This commit
- Reverts commit 8643c26a220524bf99e6f8eddef4c23b7e12dcb4.

chore(mgmt): revert add credit public endpoints (#168)

---

config/settings-env/endpoints.json

Because
- Originally, we used the `user/secrets` path for managing user secrets. However, this path style is not consistent with the pipeline endpoints. We should change it to `users/<userid>/secrets` for consistency.
This commit
- Adjusts the user secrets endpoint.

feat(vdp): adjust user secrets endpoint

---

config/settings-env/endpoints.json

Because
- The endpoints json had wrong format. 
This commit
- Fixes endpoints json.

chore(vdp): fix endpoints json

---

config/settings-env/endpoints.json

Because
- The connector and operator definition endpoints need to be guarded by auth.
This commit
- Moves connector/operator definition endpoints to auth section.

feat(vdp): move connector/operator definition endpoints to auth section

---

Makefile
config/base.json
config/settings-env/endpoints.json
config/share/templates/artifact_deprecate.tmpl
config/share/templates/mgmt.tmpl
config/share/templates/mgmt_deprecate.tmpl
config/share/templates/model.tmpl
config/share/templates/model_deprecate.tmpl
config/share/templates/pipeline.tmpl
config/share/templates/pipeline_deprecate.tmpl
plugins/multi-auth/main.go

Because
- we've unified our Core, VDP, Model and Artifact products into a single product, we no longer need to use different endpoint prefixes for them.
This commit
- removes the `/core`, `/vdp`, `/model` and `/artifact` path prefixes.
- keep the old ones as deprecated endpoints, and we'll remove them after 2024/7/31.

feat(core): remove basePath for core, vdp, model and artifact endpoints

---

config/settings-env/endpoints.json

Because
- We need to provide the info about supported regions and hardware for
FE to render the model creation page
This commit
- add list available region method

feat(model): support listing available regions for model deployment

---

config/settings-env/endpoints.json

Because
- Model page needs to support displaying custom profile image
This commit
- add endpoint to retrieve model profile image

chore(model): add get model image endpoint

---

config/settings-env/endpoints.json

Because
- We are going to support pipeline sorting.
This commit
- Adds the `order_by` parameter for pipeline endpoints.

feat(pipeline): add order_by param for pipeline endpoints

---

plugins/registry/go.mod
plugins/registry/go.sum
plugins/registry/handler.go

Because
- listUserMembership request is failing due to missing auth headers
```
[KRAKEND] 2024/05/23 - 06:20:44.630 ▶ ERROR /v2/instill-ai/llama3-8b-instruct/blobs/uploads/ failed to check organization rpc error: code = Unauthenticated desc = unauthenticated
```
This commit
- add necessary auth header to context

fix(registry): fix org membership check in registry plugin

---

plugins/registry/go.mod
plugins/registry/go.sum

Because
- registry plugin cannot be loaded
This commit
- revert protogen version upgrade

chore(registry): downgrade registry proto version

---

config/settings-env/endpoints.json

Because
- Model hub page support `order_by` option
- Model banner needs to show latest model state
This commit
- add `order_by` input query string
- add watch latest model endpoints
resolves INS-4774

feat(model): add order_by field for list model endpoints

---

config/settings-env/endpoints.json

Because
- we need to knowledge base crud endpoints in public internet
This commit
- expose the knowledge base crud http endpoints

feat(artifact): expose knowledge base endpoints

---

config/settings-env/endpoints.json

Because
- Model overview page needs to retrieve input and output data from latest model async trigger
This commit
- add endpoints to get latest operation result

chore(model): add endpoints to get latest operation result

---

Makefile
config/.env

Because
- we don't need absolute path for go plugin build
This commit
- update Makefile and clean up `.env` file

ci(Makefile): use relative paths for plugin build

---

config/settings-env/endpoints.json

Because
- Currently, our API HTTP request and response bodies are a mix of camelCase and snake_case, which is not consistent.
This commit
- The backend has used camelCase for HTTP bodies, we need to update the plugin as well.

feat(plugin): adopt multi-auth plugin to adopt the changes in /login endpoint

---

plugins/registry/handler.go

Because
- Registry endpoints on d0 produce an unauthorised error, different than dev/prod environments.
This commit
- Since the plugin doesn't log requests directly and the errors don't reach the end user (they're mediated by the Docker CLI), extra verbosity is added to the plugin.
- This will produce some noise as the CLI first tries to make unauthorised requests, then retries with credentials.

chore(artifact): add more detailed logging to registry endpoints

---

config/settings-env/endpoints.json

Because
- We should use camelCase for query strings to align with the HTTP body.
This commit
- Updates query strings to use camelCase.

feat(endpoints): use camelCase for query strings

---

plugins/grpc-proxy/go.sum
plugins/multi-auth/go.mod
plugins/multi-auth/go.sum
plugins/registry/go.mod
plugins/registry/go.sum
plugins/registry/handler.go

Because
- we are missing org deployment flow in registry plugin
This commit
- adopt org model deployment endpoint

chore(registry): adopt org model deployment endpoint

---

config/share/settings-env/input_headers.json

Because
- In order to trigger pipelines after switching namespaces, API must identify
the requester on behalf of whom the action is performed.
This commit
- Adds the requester UID header to the accepted headers.

feat(pipeline): add requester UID header

---

config/settings-env/endpoints.json

Because
- Users can now clone a pipeline from a pipeline release.
This commit
- Exposes endpoints for cloning pipeline releases.

feat(vdp): expose endpoints for cloning pipeline release

---

config/share/templates/cors.tmpl

Because
- `pipeline-backend` will parse the `Instill-Requester-Uid` header and transform
it to a system variable that will be passed to the pipeline trigger workers.
This commit
- Adds the header to the CORS configuration.

feat(pipeline): add requester header to CORS

---

config/share/templates/cors.tmpl

Because
- We need to allow the `Instill-Use-SSE` header in the CORS allow list.
This commit
- allows the `Instill-Use-SSE` header.

feat(cors): allow Instill-Use-SSE header

---

config/settings-env/endpoints.json

Because
- We'll allow users to store pipeline `profile image`.
This commit
- Exposes pipeline profile image endpoint.

feat(vdp): expose pipeline profile image endpoint

---

config/settings-env/endpoints.json

Because
chunk catalog api is implemented already. Now, we have to make api-gateway route traffic correctly.
This commit
add endpoints into krakenD.

chore(KB): add endpoint for chunk catalog

---

config/settings-env/endpoints.json

Because
1. wee need to unify the name so change owners to namespaces
2. we add new endpoint - similarity search
This commit
1. change the owners to namepsace
2. add new similarity search endpoint

feat(artifact): use namespace and add similary search api

---

config/settings-env/endpoints.json

Because
- Pipeline and credit endpoints have different params and schemas.
- Some of the information served by the existing endpoints will be handled by the logging feature.
This commit
- Applies contracts defined in https://github.com/instill-ai/protobufs/pull/387

feat(mgmt): use unified dashboard endpoints

---

plugins/multi-auth/go.mod
plugins/multi-auth/go.sum
plugins/registry/go.mod
plugins/registry/go.sum
plugins/registry/handler.go

Because
- Previously, we used a general name parameter in request parameters, e.g., {name=users/*}, which was ambiguous.
This commit
- use explicit user_id in request
- adopt namespace endpoints

feat(registry): adopt namespace endpoint

---

config/settings-env/endpoints.json

Because
- The new dashboard endpoints introduced breaking changes and the clients won't be ready for the upcoming release.
This commit
- Restores the previous dashboard endpoints
- `ListPipelineTriggerRecords` isn't added back as it had no clients.

fix(mgmt): restore pipeline dashboard enpoints

---

config/share/templates/artifact.tmpl

Because
- The Artifact gRPC endpoints were not correctly exposed.
This commit
- Fixes gRPC endpoints exposure.

fix(artifact): fix gRPC endpoints not correctly exposed

---

plugins/registry/handler.go

Because
- Comparing `Organization.Name` with formant `organizations/{id}` to `namespace` with format `{id}` will always result in false, causing organization model not able to be pushed.
This commit
- fix wrong namespace format comparison

fix(registry): fix wrong namespace format comparison

---

config/settings-env/endpoints.json

Because
there is a typo in file catalog api
This commit
fix it

fix(catalog): fix typo in file catalog api

---

.gitignore
config/settings-env/endpoints.json

Because
- FE needs to access model run logging endpoint
This commit
- added model run logging endpoint

feat(model): added model run logging endpoint

---

config/settings-env/endpoints.json

Because
- wrong model endpoint version
- missing grpc endpoint
This commit
- fix wrong version and add missing grpc endpoint

fix(model): fix wrong version and add missing grpc endpoint

---

config/settings-env/endpoints.json

Because
- model backend point prefix should be v1alpha
This commit
- fixed model backend point prefix

feat(model): fixed model run logging endpoint prefix

---

config/share/settings-env/input_headers.json
config/share/templates/cors.tmpl

Because
- The `Instill-User-Agent` header need to be added to the header allow-list.
This commit
- Adds `Instill-User-Agent` into header list.

chore(vdp,model): add Instill-User-Agent into header list

---

config/settings-env/endpoints.json

Because
- Some instill model's endpoints are deprecated
- add endpoint for getting namespace model operation with particular version
This commit
- add operation endpoint and remove unused endpoints

chore(model): add operation endpoint and remove unused endpoints

---

config/share/settings-env/input_headers.json
config/share/templates/cors.tmpl
plugins/grpc-proxy/server.go
plugins/multi-auth/main.go
plugins/sse-streaming/main.go

Because
- We should use the common `Accept` header to determine the response content type as `text/event-stream`.
This commit
- Uses the `Accept` header to identify and handle `text/event-stream`.

feat(vdp): use the `Accept` header to identify and handle `text/event-stream`

---

config/settings-env/endpoints.json

Because
- namespace asynchronous trigger endpoint path does not align with protobuf definition
This commit
- update trigger path

chore(trigger): update trigger path

---

config/settings-env/endpoints.json

Because
- https://github.com/instill-ai/pipeline-backend/pull/611 implements some public
endpoints.
This commit
- Exposes the integration read endpoints.

feat(pipeline): add integration read endpoints

---

config/settings-env/endpoints.json

Because
- With the integration endpoints, users can fetch the schemas to create connection resources.
This commit
- Opens the creation and view endpoints for connections.

feat(pipeline): add connection create and get endpoints

---

config/settings-env/endpoints.json

Because
- Some endpoints defined in the Instill Integration Milestone 1 weren't exposed yet.
This commit
- Add the missing endpoints to the gateway configuration.

feat(pipeline): expose integration endpoints

---

.github/workflows/integration-test.yml

Because
- Integration tests use `xk6` to run a SQL plugin.
This commit
- Update GitHub action to install `xk6` SQL plugin.

chore(test): add xk6 to integration test action

---

config/settings-env/endpoints.json

Because
FE needs to fetch chunks by uid
This commit
add it in query string

feat(artifact): add chunk uid in query string

---

config/settings-env/endpoints.json

Because
- The trigger endpoint timeout is too short
This commit
- Increases the trigger timeout

chore(vdp): increase trigger timeout

---

config/settings-env/endpoints.json

Because
- The `GetNamespaceConnection` endpoint returns `UNIMPLEMENTED`.
This commit
- Fix route.

fix(connection): fix GetNamespaceConnection route

---

config/settings-env/endpoints.json

Because
- Pipeline metrics list endpoint was removed but it has a client.
This commit
- Reintroduces the endpoint contract. It will be removed with the new
dashboard design.

fix(metric): reintroduce /metrics/vdp/pipeline/triggers endpoint

---

.github/workflows/integration-test.yml

Because
- https://github.com/instill-ai/pipeline-backend/pull/791 introduced a environment variable dependency in the integration tests.
This commit
- Adds the environment variable to `instill-cloud` setup in CI.

chore(test): inject variables to `instill-core` to test OAuth support

---

config/settings-env/endpoints.json

Because
- dashboard needs new APIs for model/pipeline runs and metrics
This commit
- add pipeline/model runs and metrics APIs

feat(run): pipeline/model runs and metrics APIs

---

plugins/blob/handler.go
plugins/multi-auth/main.go

Because
blob plugin is using multi-auth plugin for user authn including jwt token.
This commit
adds the user'd uuid in the blob upload and download request for blob plugin.

fix(blob): blob support authn by jwt token

---

config/settings-env/endpoints.json

Because
- A new webhook dispatcher endpoint has been added.
This commit
- Exposes the webhook dispatcher endpoint.

feat(vdp): expose webhook dispatcher endpoint

---

config/settings-env/endpoints.json

Because
- the operator and connector-definition endpoints are deprecated; users should use the component-definition endpoints instead.
This commit
- removes deprecated operator and connector-definition endpoints

chore(vdp): remove deprecated operator and connector-definition endpoints

---

config/settings-env/endpoints.json

Because
- The old webhook endpoints are deprecated and no longer in use.
This commit
- Removes the outdated webhook endpoints.

chore(vdp): remove old webhook endpoints

---

config/.env.envsubst
config/settings-env/endpoints.json

Because
In the one minute impact, the user can move a file from one catalog to another.
This commit
Adds the endpoint to the API gateway.

feat(artifact): add move file endpoint

---

config/settings-env/endpoints.json

Because
- Agent needs summary for RAG/high-recall
This commit
- add get summary for catalog file

feat(artifact): add get summary endpoint

---

Dockerfile

This commit
- adds a default KRAKEND_CE_VERSION, so we don’t need to provide this value from docker-compose in instill-core.

chore(docker): add default KRAKEND_CE_VERSION

---

config/settings-env/endpoints.json

Because
- we have a new GetCatalogFile endpoint.
This commit
- exposes GetCatalogFile endpoint.

chore(artifact): expose GetCatalogFile endpoint

---

plugins/blob/go.mod
plugins/blob/go.sum
plugins/blob/handler.go
plugins/blob/main.go
plugins/registry/handler.go
plugins/registry/main.go

Because
- 2 vulnerabilities related to log injection have been detected:
- https://github.com/instill-ai/api-gateway/security/code-scanning/7
- https://github.com/instill-ai/api-gateway/security/code-scanning/6
This commit
- Escapes input URL paths and headers before logging them
- Unifies the logging strategy across plugins

fix(security): escape request paths to avoid log injection

---

.github/workflows/releases.yml
release-please/config.json

Because
- We have to upgrade the release-please action in ga workflow
This commit
- upgrade the release-please action in ga workflow

ci(workflow): upgrade the release-please action in ga workflow

---

Dockerfile

Because
- The official `musl` download link is blocked by GitHub Actions
This commit
- Updates the `musl` address to use self-hosted storage

ci(docker): update `musl` toolchain download address

---

plugins/blob/handler.go

Because
- we want the file to be previewed in the browser
This commit
- allows the file to be previewed in the browser by setting the `Content-Disposition` header to `inline`

chore(blob): allow file be previewed in browser

---

plugins/blob/main.go

Because
- we want to simplify file upload/download flows by leveraging MinIO’s built-in authentication and expiration mechanisms in the pre-signed URL
This commit
- decodes the new blob-url and directly forward it to MinIO

feat(plugin): support new blob-url path
