instill-ai/api-gateway

.github/workflows/codeql.yml
.github/workflows/releases.yml
config/settings-env/endpoints.json

Because
- the mgmt protouf has been updated
This commit
- adopts the latest mgmt protobuf

chore: adopt latest mgmt-backend endpoints

---

Makefile
README.md
config/settings-env/endpoints.json

Because
- we want to adopt the latest protobuf for API token (not implemented)
This commit
- expose token endpoints

chore(mgmt): expose token endpoints

---

config/settings-env/endpoints.json

Because
- the grpc service names are out of date
This commit
- update grpc service names

fix(endpoints): update service name

---

config/settings-env/endpoints.json

Because
- add test connection method in connector-backend
- remove temporal in connector-backend
This commit
- add POST test connection method
- prolong timeout for sync write method

chore(connector): add testConnection and update write

---

.github/workflows/integration-test.yml

Because
- update integration-test mode
This commit
- update integration-test mode

chore(workflow): fix integration-test mode

---

.github/workflows/integration-test.yml
Makefile

Because
- retire `ITMODE` and change to `ITMODE_ENABLED` in VDP
This commit
- update `ITMODE` naming
Fixes INS-866

chore(env): update `ITMODE` naming in VDP

---

config/envsubst.sh

Because
- accommodate api-gateway hostname from helm
This commit
- update command that extract project name from hostname

chore: update command that resolve project name

---

.github/workflows/integration-test.yml
config/base/settings-env/endpoints.json

Because
- we want to expose pipeline releases endpoints
This commit
- add pipeline releases endpoints
- fix workflow env params bug

chore(pipeline): add pipeline releases endpoints

---

Dockerfile
Dockerfile.dev
Makefile
config/base/settings-env/endpoints.json
config/share/settings-env/input_headers.json
config/share/templates/auth_validator.tmpl
config/share/templates/connector.tmpl
config/share/templates/mgmt.tmpl
config/share/templates/model.tmpl
config/share/templates/pipeline.tmpl
scripts/generate_jwks.sh

Because
- we are going to support simple authentication in Instill-Core
This commit
- add auth/signer and auth/validator
- add `jwx` to generate JWKS file

feat(auth): add auth/signer and auth/validator

---

config/settings-env/endpoints.json

Because
- we've introduced new organization endpoints for ACL and organization management
This commit
- add organization endpoints

feat(core): add organization endpoints

---

config/settings-env/endpoints.json

Because
- we need to allow user to create pipeline/connector under organization namespace
This commit
- add organization API endpoints

feat(vdp): add organization pipeline and connector endpoints

---

config/base.json
config/settings-env/endpoints.json
multi_auth_plugin/server/main.go

Because
- we are going to release beta version of Core and VDP
This commit
- upgrade Core and VDP version to v1beta

feat(core,vdp): upgrade endpoints version from v1alpha to v1beta

---

.github/CODEOWNERS
.github/workflows/integration-test.yml

Because
- the integration test needs to be updated to adopt the latest `instill-core` project structure
This commit
- update the `integration-test.yml` file

ci(workflows): update integration test

---

plugins/registry/main.go

Because
- We want to check if `namespace` is present in docker push URL
- Some requests might be missing auth `username`
This commit
- add back `username` empty string check
- add `namespace` section check in regex

chore(registry): update regex check for namespace

---

config/base.json
config/settings-env/endpoints.json
config/settings-env/plugins.json
plugins/registry/handler.go

Because
- we will prevent image from pushing if the namespace does not exist
This commit
- add namespace check in registry plugin
- adopt latest model-backend protobuf
resolves INS-4023

feat(model): add namespace check and adopt latest protobuf

---

config/settings-env/endpoints.json

Because
- Support listing model versions for a particular model namespace
This commit
- add ListModelVersions method
- update version related paths

chore(model): add list model versions and update version path

---

config/settings-env/endpoints.json

Because
- Model page UI needs to allow user to search and filter
This commit
- add `visibility` and `filter` in list model endpoints

chore(model): support filter in list model endpoints

---

config/settings-env/endpoints.json

Because
- Support triggering model without specifying version
This commit
- add endpoint to trigger latest model version

feat(model): support trigger latest model version

---

config/settings-env/endpoints.json

Because
path conflict 
This commit
use user_id instead of uid
Notes:
not sure why using uid cause conflic. look into it later.

fix(kb): endpoint conflict

---

config/settings-env/endpoints.json

Because
artifact backend has completed the knowledge base files api, we need to set the gateway for endpoint.
This commit
set the knowledge base files api endpoints.

feat(kb): support knowledge base file related api

---

.github/workflows/integration-test.yml

Because
- PR test ci won't use the source branch for integration-test
This commit
- fix PR test workflow by using pr branch head to build the test image

ci(workflows): fix PR test workflow

---

.gitignore
config/settings-env/endpoints.json

Because
knowledge base endpoint need to support namespace
This commit
add owner_id in path parameter

chore(kb): modify endpoints of kb

---

config/settings-env/endpoints.json

Because
- We are going to support model version deletion
This commit
- add model version deletion endpoints

feat(model): add model version deletion endpoints

---

Dockerfile

Because
- The SSE streaming plugin needs to be compiled in the Docker image.
This commit
- Adds the SSE streaming plugin to the Dockerfile.

chore(dockerfile): add sse-streaming plugin in Dockerfile

---

config/settings-env/endpoints.json

Because
- We'd like to simplify the API endpoints by merging users and organization endpoints into namespace endpoints.
This commit
- Introduces new namespace endpoints.

feat(vdp,model): expose namespace endpoints

---

config/settings-env/endpoints.json

Because
need longer timeout
This commit
change to 60s for file uploading

fix(kb): upload file timeout

---

config/settings-env/endpoints.json
config/share/settings-env/input_headers.json
config/share/templates/pipeline.tmpl

Because
- We are introducing the functionality for a pipeline to be run on events.
This commit
- Exposes run-on-event endpoints.

feat(vdp): expose run-on-event endpoints

---

config/settings-env/endpoints.json

Because
we need to rename from kb to catalog
This commit
renames from kb to catalog

feat(catalog): rename endpoint from kb to catalog

---

config/settings-env/endpoints.json

Because
we need to support file catalog and question answering endpoint
This commit
add file catalog and question answering endpoint

feat(catalog): add file catalog and question answering endpoint

---

config/settings-env/endpoints.json

Because
- we need new pipeline & component endpoints for FE
This commit
- add new pipeline & component endpoints

feat(vdp): added pipeline run logging endpoints

---

config/settings-env/endpoints.json

Because
catalog is about to support conversations and messages
This commit
adds conversations and messages endpoints

feat(catalog): add conversations and messages endpoints

---

config/settings-env/endpoints.json

task mentioned here: https://github.com/instill-ai/api-gateway-cloud/pull/273#issuecomment-2306461819
Because
- we need new pipeline & component endpoints for FE
This commit
- add new grpc pipeline & component endpoints

feat(vdp): add grpc pipeline run logging endpoints

---

config/settings-env/endpoints.json

Because
we no longer need the conversation and message in artifact.
This commit
removes the conv/message api in artifact

chore(artifact): clean up conversation 

---

config/settings-env/endpoints.json

Because
wee need the endpoints for blob
This commit
adds the necessary endpoints

feat(blob): add blob endpoint

---

config/settings-env/endpoints.json

Because
artifact need the search chunk and source endpoint
This commit
adds those endpoints

feat(artifact): support search chunk & source

---

.github/workflows/integration-test.yml
config/settings-env/endpoints.json

This commit
- renames `vdp` to `pipeline`

feat(all): rename VDP to pipeline

---

plugins/blob/handler.go

Because
- We need to add the origin and user UID headers to the presigned URLs so we can track who accesses user data on MinIO.
This commit
- Adds a pre-established agent header to MinIO presigned URL requests.

feat(minio): add agent header to presigned URLs

---

.github/CONTRIBUTING.md
.github/workflows/images.yml
.github/workflows/integration-test.yml

This commit
- adopts latest Makefile command in integration test

ci(test): adopts latest Makefile command in integration test

---

config/settings-env/endpoints.json

This commit
- Adds param defined in https://github.com/instill-ai/protobufs/pull/661

feat(kbfile): add status filter to catalog file list
